version: '3.0'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: send_it_development
      POSTGRES_USER: send_it
      POSTGRES_PASSWORD: password

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: send_it_development
      DATABASE_USER: send_it
      DATABASE_PASSWORD: password
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true

volumes:
  postgres_data: